# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dff8675afebdcd0238fabdbbe157d4a3b71e8ae1314cd519e0a4fac93f5ca913398c306d3590dd076edcc56b84d2ff0a59865f1564673d6a92d54471e1b987db

test:
  secret_key_base: 45ad0ffc48a7ac7146535b46f25dc64dc17c59de6116ef7942f0e2e3979bb595cbaee6aedb309711de11942aa43827ebbce7e2bb214a5fab0ad7ae1a2466f72d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
